app/config/routes.rb
Rails.application.routes.draw do
  resources :medals

end

app/app/models/medal.rb
class Medal < ActiveRecord::Base
    validates :athlete_name, presence: true
    validates :country, presence: true
    medal_types = ['gold', 'silver', 'bronze']
    validates :medal_type, inclusion: { in: %w(gold silver bronze),
        message: "%{value} is not a valid medal_type" }
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/app/controllers/medals_controller.rb
class MedalsController < ApplicationController
  before_action :set_medal, only: [:show, :edit, :update, :destroy]

  # GET /medals
  # GET /medals.json
  def index
    @medals = Medal.all
  end

  # GET /medals/1
  # GET /medals/1.json
  def show
  end

  # GET /medals/new
  def new
    @medal = Medal.new
  end

  # GET /medals/1/edit
  def edit
  end

  # POST /medals
  # POST /medals.json
  def create
    @medal = Medal.new(medal_params)

    respond_to do |format|
      if @medal.save
        format.html { redirect_to @medal, notice: 'Medal was successfully created.' }
        format.json { render :show, status: :created, location: @medal }
      else
        format.html { render :new }
        format.json { render json: @medal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medals/1
  # PATCH/PUT /medals/1.json
  def update
    respond_to do |format|
      if @medal.update(medal_params)
        format.html { redirect_to @medal, notice: 'Medal was successfully updated.' }
        format.json { render :show, status: :ok, location: @medal }
      else
        format.html { render :edit }
        format.json { render json: @medal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medals/1
  # DELETE /medals/1.json
  def destroy
    @medal.destroy
    respond_to do |format|
      format.html { redirect_to medals_url, notice: 'Medal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medal
      @medal = Medal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medal_params
      params.require(:medal).permit(:athlete_name, :event, :country, :medal_type, :event_date)
    end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/medals_helper.rb
module MedalsHelper
end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/app/views/medals/_form.html.erb
<%= form_for(@medal) do |f| %>
  <% if @medal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medal.errors.count, "error") %> prohibited this medal from being saved:</h2>

      <ul>
      <% @medal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :athlete_name %><br>
    <%= f.text_field :athlete_name %>
  </div>
  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :medal_type %><br>
    <%= f.select(:medal_type, [["gold", "gold"], ["silver","silver"], ["bronze", "bronze"]]) %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.datetime_select :event_date, :start_year => 2012, :end_year => 2012 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/app/views/medals/edit.html.erb
<h1>Editing Medal</h1>

<%= render 'form' %>

<%= link_to 'Show', @medal %> |
<%= link_to 'Back', medals_path %>

app/app/views/medals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Medals</h1>

<table>
  <thead>
    <tr>
      <th>Athlete name</th>
      <th>Event</th>
      <th>Country</th>
      <th>Medal type</th>
      <th>Event date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medals.each do |medal| %>
      <tr>
        <td><%= medal.athlete_name %></td>
        <td><%= medal.event %></td>
        <td><%= medal.country %></td>
        <td><%= medal.medal_type %></td>
        <td><%= medal.event_date %></td>
        <td><%= link_to 'Show', medal %></td>
        <td><%= link_to 'Edit', edit_medal_path(medal) %></td>
        <td><%= link_to 'Destroy', medal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medal', new_medal_path %>

app/app/views/medals/new.html.erb
<h1>New Medal</h1>

<%= render 'form' %>

<%= link_to 'Back', medals_path %>

app/app/views/medals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Athlete name:</strong>
  <%= @medal.athlete_name %>
</p>

<p>
  <strong>Event:</strong>
  <%= @medal.event %>
</p>

<p>
  <strong>Country:</strong>
  <%= @medal.country %>
</p>

<p>
  <strong>Medal type:</strong>
  <%= @medal.medal_type %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @medal.event_date %>
</p>

<%= link_to 'Edit', edit_medal_path(@medal) %> |
<%= link_to 'Back', medals_path %>